// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1372556_ProjetFinal.Data;

#nullable disable

namespace _1372556_ProjetFinal.Migrations
{
    [DbContext(typeof(TP1_PokemonContext))]
    [Migration("20231102193252_TP2")]
    partial class TP2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_1372556_ProjetFinal.Models.Dresseur", b =>
                {
                    b.Property<int>("IdDresseur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDresseur");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDresseur"), 1L, 1);

                    b.Property<int?>("BadgeCount")
                        .HasColumnType("int")
                        .HasColumnName("badgeCount");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("prenom");

                    b.HasKey("IdDresseur")
                        .HasName("PK__Dresseur__A18A258796FF75EA");

                    b.ToTable("Dresseur");
                });

            modelBuilder.Entity("_1372556_ProjetFinal.Models.Generation", b =>
                {
                    b.Property<int>("IdGeneration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idGeneration");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGeneration"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom");

                    b.Property<int>("NombreJeux")
                        .HasColumnType("int")
                        .HasColumnName("nombreJeux");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("numero");

                    b.HasKey("IdGeneration")
                        .HasName("PK__Generati__B9B517B5C22F9B78");

                    b.ToTable("Generation");
                });

            modelBuilder.Entity("_1372556_ProjetFinal.Models.Jeux", b =>
                {
                    b.Property<int>("IdJeux")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idJeux");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJeux"), 1L, 1);

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<DateTime?>("DateSortie")
                        .HasColumnType("date")
                        .HasColumnName("dateSortie");

                    b.Property<int?>("IdGeneration")
                        .HasColumnType("int")
                        .HasColumnName("idGeneration");

                    b.Property<string>("NomJeu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nomJeu");

                    b.HasKey("IdJeux")
                        .HasName("PK__Jeux__1087CF56308CDE1D");

                    b.HasIndex("IdGeneration");

                    b.ToTable("Jeux");
                });

            modelBuilder.Entity("_1372556_ProjetFinal.Models.Pokemon", b =>
                {
                    b.Property<int>("IdPokemon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPokemon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPokemon"), 1L, 1);

                    b.Property<int?>("IdGeneration")
                        .HasColumnType("int")
                        .HasColumnName("idGeneration");

                    b.Property<int?>("Niveau")
                        .HasColumnType("int")
                        .HasColumnName("niveau");

                    b.Property<int?>("NiveauParDefaut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("niveauParDefaut")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom");

                    b.HasKey("IdPokemon")
                        .HasName("PK__Pokemon__653EBD85BAB59545");

                    b.HasIndex("IdGeneration");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("_1372556_ProjetFinal.Models.Types", b =>
                {
                    b.Property<int>("IdTypes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idType");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTypes"), 1L, 1);

                    b.Property<string>("NomType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nomType");

                    b.HasKey("IdTypes")
                        .HasName("PK__Type__4BB98BC6ED3EF932");

                    b.HasIndex(new[] { "NomType" }, "UQ__Type__C90762B7BEDFB1CC")
                        .IsUnique();

                    b.ToTable("Type");
                });

            modelBuilder.Entity("DresseurPokemon", b =>
                {
                    b.Property<int>("IdDresseur")
                        .HasColumnType("int");

                    b.Property<int>("IdPokemon")
                        .HasColumnType("int");

                    b.HasKey("IdDresseur", "IdPokemon");

                    b.ToTable("DresseurPokemon");
                });

            modelBuilder.Entity("PokemonDresseur", b =>
                {
                    b.Property<int>("IdPokemon")
                        .HasColumnType("int")
                        .HasColumnName("idPokemon");

                    b.Property<int>("IdDresseur")
                        .HasColumnType("int")
                        .HasColumnName("idDresseur");

                    b.HasKey("IdPokemon", "IdDresseur")
                        .HasName("PK__Pokemon___0F261FDD8599F6D7");

                    b.HasIndex("IdDresseur");

                    b.ToTable("Pokemon_Dresseur", (string)null);
                });

            modelBuilder.Entity("PokemonTypes", b =>
                {
                    b.Property<int>("IdPokemon")
                        .HasColumnType("int")
                        .HasColumnName("idPokemon");

                    b.Property<int>("IdTypes")
                        .HasColumnType("int")
                        .HasColumnName("idTypes");

                    b.Property<int>("IdType")
                        .HasColumnType("int");

                    b.HasKey("IdPokemon", "IdTypes")
                        .HasName("PK__PokemonT__1185253979228652");

                    b.HasIndex("IdTypes");

                    b.ToTable("PokemonTypes", (string)null);
                });

            modelBuilder.Entity("_1372556_ProjetFinal.Models.Jeux", b =>
                {
                    b.HasOne("_1372556_ProjetFinal.Models.Generation", "IdGenerationNavigation")
                        .WithMany("Jeuxes")
                        .HasForeignKey("IdGeneration")
                        .HasConstraintName("fk_Generation_jeux");

                    b.Navigation("IdGenerationNavigation");
                });

            modelBuilder.Entity("_1372556_ProjetFinal.Models.Pokemon", b =>
                {
                    b.HasOne("_1372556_ProjetFinal.Models.Generation", "IdGenerationNavigation")
                        .WithMany("Pokemons")
                        .HasForeignKey("IdGeneration")
                        .HasConstraintName("fk_Generation");

                    b.Navigation("IdGenerationNavigation");
                });

            modelBuilder.Entity("PokemonDresseur", b =>
                {
                    b.HasOne("_1372556_ProjetFinal.Models.Dresseur", null)
                        .WithMany()
                        .HasForeignKey("IdDresseur")
                        .IsRequired()
                        .HasConstraintName("fk_Dresseur");

                    b.HasOne("_1372556_ProjetFinal.Models.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("IdPokemon")
                        .IsRequired()
                        .HasConstraintName("fk_Pokemon");
                });

            modelBuilder.Entity("PokemonTypes", b =>
                {
                    b.HasOne("_1372556_ProjetFinal.Models.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("IdPokemon")
                        .IsRequired()
                        .HasConstraintName("fk_Pokemon_type");

                    b.HasOne("_1372556_ProjetFinal.Models.Types", null)
                        .WithMany()
                        .HasForeignKey("IdTypes")
                        .IsRequired()
                        .HasConstraintName("fk_Type");
                });

            modelBuilder.Entity("_1372556_ProjetFinal.Models.Generation", b =>
                {
                    b.Navigation("Jeuxes");

                    b.Navigation("Pokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
